package google

import (
	"time"

	"github.com/vitaliiPsl/crappy-adk/kit"
)

var knownModels = []kit.ModelConfig{
	{
		ID:            "gemini-3.1-pro-preview",
		Provider:      providerID,
		ContextWindow: 1_048_576,
		InputLimit:    1_048_576,
		OutputLimit:   65_536,
		Cost: kit.ModelCost{
			Input:     2.00,
			Output:    12.00,
			CacheRead: 0.20,
		},
		Capabilities: kit.ModelCapabilities{
			Text:      true,
			Image:     true,
			Audio:     true,
			Video:     true,
			PDF:       true,
			Tools:     true,
			Streaming: true,
			Reasoning: true,
			Caching:   true,
			Batch:     true,
		},
		KnowledgeCutoff: time.Date(2025, 1, 1, 0, 0, 0, 0, time.UTC),
		ReleaseDate:     time.Date(2026, 2, 19, 0, 0, 0, 0, time.UTC),
	},
	{
		ID:            "gemini-3.1-flash-lite-preview",
		Provider:      providerID,
		ContextWindow: 1_048_576,
		InputLimit:    1_048_576,
		OutputLimit:   65_536,
		Cost: kit.ModelCost{
			Input:     0.50,
			Output:    3.00,
			CacheRead: 0.05,
		},
		Capabilities: kit.ModelCapabilities{
			Text:      true,
			Image:     true,
			Audio:     true,
			Video:     true,
			PDF:       true,
			Tools:     true,
			Streaming: true,
			Reasoning: true,
			Caching:   true,
			Batch:     true,
		},
		KnowledgeCutoff: time.Date(2025, 1, 1, 0, 0, 0, 0, time.UTC),
		ReleaseDate:     time.Date(2026, 3, 3, 0, 0, 0, 0, time.UTC),
	},
	{
		ID:            "gemini-3-pro-preview",
		Provider:      providerID,
		ContextWindow: 1_000_000,
		InputLimit:    1_000_000,
		OutputLimit:   64_000,
		Cost: kit.ModelCost{
			Input:     2.00,
			Output:    12.00,
			CacheRead: 0.20,
		},
		Capabilities: kit.ModelCapabilities{
			Text:      true,
			Image:     true,
			Audio:     true,
			Video:     true,
			PDF:       true,
			Tools:     true,
			Streaming: true,
			Reasoning: true,
			Caching:   true,
			Batch:     true,
		},
		KnowledgeCutoff: time.Date(2025, 1, 1, 0, 0, 0, 0, time.UTC),
		ReleaseDate:     time.Date(2025, 11, 18, 0, 0, 0, 0, time.UTC),
	},
	{
		ID:            "gemini-3-flash-preview",
		Provider:      providerID,
		ContextWindow: 1_048_576,
		InputLimit:    1_048_576,
		OutputLimit:   65_536,
		Cost: kit.ModelCost{
			Input:     0.50,
			Output:    3.00,
			CacheRead: 0.05,
		},
		Capabilities: kit.ModelCapabilities{
			Text:      true,
			Image:     true,
			Audio:     true,
			Video:     true,
			PDF:       true,
			Tools:     true,
			Streaming: true,
			Reasoning: true,
			Caching:   true,
			Batch:     true,
		},
		KnowledgeCutoff: time.Date(2025, 1, 1, 0, 0, 0, 0, time.UTC),
		ReleaseDate:     time.Date(2025, 12, 17, 0, 0, 0, 0, time.UTC),
	},
	{
		ID:            "gemini-2.5-pro",
		Provider:      providerID,
		ContextWindow: 1_048_576,
		InputLimit:    1_048_576,
		OutputLimit:   65_536,
		Cost: kit.ModelCost{
			Input:     1.25,
			Output:    10.00,
			CacheRead: 0.31,
		},
		Capabilities: kit.ModelCapabilities{
			Text:      true,
			Image:     true,
			Audio:     true,
			Video:     true,
			PDF:       true,
			Tools:     true,
			Streaming: true,
			Reasoning: true,
			Caching:   true,
			Batch:     true,
		},
		KnowledgeCutoff: time.Date(2025, 1, 1, 0, 0, 0, 0, time.UTC),
		ReleaseDate:     time.Date(2025, 3, 20, 0, 0, 0, 0, time.UTC),
	},
	{
		ID:            "gemini-2.5-flash",
		Provider:      providerID,
		ContextWindow: 1_048_576,
		InputLimit:    1_048_576,
		OutputLimit:   65_536,
		Cost: kit.ModelCost{
			Input:     0.30,
			Output:    2.50,
			CacheRead: 0.075,
		},
		Capabilities: kit.ModelCapabilities{
			Text:      true,
			Image:     true,
			Audio:     true,
			Video:     true,
			PDF:       true,
			Tools:     true,
			Streaming: true,
			Reasoning: true,
			Caching:   true,
			Batch:     true,
		},
		KnowledgeCutoff: time.Date(2025, 1, 1, 0, 0, 0, 0, time.UTC),
		ReleaseDate:     time.Date(2025, 3, 20, 0, 0, 0, 0, time.UTC),
	},
}
