package kit

import (
	"context"
)

// Provider is a factory for creating models from a specific AI provider.
type Provider interface {
	// Model returns the model with the given ID, or an error if it is unknown.
	Model(id string) (Model, error)

	// Models returns all models supported by this provider.
	Models() ([]ModelConfig, error)
}

// Model is a single AI model capable of generating responses.
type Model interface {
	// Config returns the static configuration for this model.
	Config() ModelConfig

	// Generate sends a request to the model and returns its response.
	Generate(ctx context.Context, req ModelRequest) (ModelResponse, error)
}

// ModelConfig holds static metadata for a model.
type ModelConfig struct {
	// ID is the model identifier used when calling the provider API.
	ID string

	// Provider is the name of the provider that owns this model.
	Provider string

	// ContextWindow is the maximum number of input tokens the model accepts.
	ContextWindow int

	// MaxOutputTokens is the maximum number of tokens the model can generate.
	MaxOutputTokens int

	// InputPricePerM is the cost in USD per million input tokens.
	InputPricePerM float64

	// OutputPricePerM is the cost in USD per million output tokens.
	OutputPricePerM float64
}

// ModelRequest is the input to a model generation call.
type ModelRequest struct {
	// Instructions is the system prompt passed to the model.
	Instructions string

	// Messages is the conversation history.
	Messages []Message

	// Tools is the set of available tools.
	Tools []ToolDefinition
}

// ModelResponse is the output of a model generation call.
type ModelResponse struct {
	// Content is the text generated by the model.
	Content string

	// ToolCalls are the tool invocations requested by the model, if any.
	ToolCalls []ToolCall
}
