package kit

import (
	"context"
	"iter"
)

// Provider is a factory for creating models from a specific AI provider.
type Provider interface {
	// Model returns the model with the given ID, or an error if it is unknown.
	Model(id string) (Model, error)

	// Models returns all models supported by this provider.
	Models() ([]ModelConfig, error)
}

// Model is a single AI model capable of generating responses.
type Model interface {
	// Config returns the static configuration for this model.
	Config() ModelConfig

	// Generate sends a request to the model and returns its response.
	Generate(ctx context.Context, req ModelRequest) (ModelResponse, error)

	// GenerateStream sends a request to the model and streams the response as
	// a sequence of chunks. The iterator yields an error and stops on failure.
	GenerateStream(ctx context.Context, req ModelRequest) iter.Seq2[ModelChunk, error]
}

// ModelConfig holds static metadata for a model.
type ModelConfig struct {
	// ID is the model identifier used when calling the provider API.
	ID string

	// Provider is the name of the provider that owns this model.
	Provider string

	// ContextWindow is the maximum number of input tokens the model accepts.
	ContextWindow int

	// MaxOutputTokens is the maximum number of tokens the model can generate.
	MaxOutputTokens int

	// InputPricePerM is the cost in USD per million input tokens.
	InputPricePerM float64

	// OutputPricePerM is the cost in USD per million output tokens.
	OutputPricePerM float64
}

// ModelRequest is the input to a model generation call.
type ModelRequest struct {
	// Instructions is the system prompt passed to the model.
	Instructions string

	// Messages is the conversation history.
	Messages []Message

	// Tools is the set of available tools.
	Tools []ToolDefinition

	// Config controls generation parameters. Zero value uses model defaults.
	Config GenerationConfig
}

// ModelResponse is the output of a model generation call.
type ModelResponse struct {
	// Content is the text generated by the model.
	Content string

	// Thinking is the reasoning produced when extended thinking is enabled.
	Thinking string

	// ToolCalls are the tool invocations requested by the model, if any.
	ToolCalls []ToolCall

	// FinishReason indicates why the model stopped generating.
	FinishReason FinishReason

	// Usage reports token consumption for this call.
	Usage Usage
}

// ModelChunk is a single incremental piece of a streamed model response.
type ModelChunk struct {
	// Text is an incremental text token. May be empty if the chunk only carries
	// tool calls or thinking tokens.
	Text string

	// Thinking is an incremental thinking token. Only populated when extended
	// thinking is enabled.
	Thinking string

	// ToolCalls are the complete tool invocations requested by the model.
	// Populated only at the end of the stream, once all tool calls are known.
	ToolCalls []ToolCall

	// FinishReason is set on the final chunk to indicate why the model stopped.
	FinishReason FinishReason

	// Usage reports token consumption. Set on the final chunk.
	Usage Usage
}

// GenerationConfig controls how the model generates its response.
// All fields are optional; unset fields use the model's defaults.
type GenerationConfig struct {
	// Temperature controls randomness. Higher values produce more varied output.
	Temperature *float32

	// TopP limits sampling to the smallest set of tokens whose cumulative
	// probability meets this threshold.
	TopP *float32

	// MaxOutputTokens limits the number of tokens the model can generate.
	MaxOutputTokens *int32

	// Thinking controls extended thinking. Defaults to ThinkingDisabled.
	Thinking ThinkingLevel
}

// ThinkingLevel controls how much reasoning effort the model applies.
type ThinkingLevel string

const (
	// ThinkingDisabled turns off extended thinking. This is the default.
	ThinkingDisabled ThinkingLevel = ""
	// ThinkingLevelLow applies minimal reasoning, faster and cheaper.
	ThinkingLevelLow ThinkingLevel = "low"
	// ThinkingLevelMedium applies moderate reasoning.
	ThinkingLevelMedium ThinkingLevel = "medium"
	// ThinkingLevelHigh applies thorough reasoning, slower and more expensive.
	ThinkingLevelHigh ThinkingLevel = "high"
)

// FinishReason indicates why the model stopped generating.
type FinishReason string

const (
	// FinishReasonStop means the model reached a natural stopping point.
	FinishReasonStop FinishReason = "stop"
	// FinishReasonMaxTokens means the output token limit was reached.
	FinishReasonMaxTokens FinishReason = "max_tokens"
	// FinishReasonToolCall means the model is requesting one or more tool calls.
	FinishReasonToolCall FinishReason = "tool_call"
	// FinishReasonSafety means the response was blocked by a safety filter.
	FinishReasonSafety FinishReason = "safety"
	// FinishReasonUnknown means the stop reason was not recognised.
	FinishReasonUnknown FinishReason = "unknown"
)

// Usage reports the number of tokens consumed by a model call.
type Usage struct {
	// InputTokens is the number of tokens in the request.
	InputTokens int32

	// OutputTokens is the number of tokens generated in the response.
	OutputTokens int32
}
