package anthropic

import (
	"time"

	"github.com/vitaliiPsl/crappy-adk/kit"
)

var knownModels = []kit.ModelConfig{
	{
		ID:            "claude-opus-4-6",
		Provider:      ProviderID,
		ContextWindow: 200_000,
		InputLimit:    200_000,
		OutputLimit:   128_000,
		Cost: kit.ModelCost{
			Input:      5.00,
			Output:     25.00,
			CacheRead:  0.50,
			CacheWrite: 6.25,
		},
		Capabilities: kit.ModelCapabilities{
			Text:      true,
			Image:     true,
			PDF:       true,
			Tools:     true,
			Streaming: true,
			Reasoning: true,
			Caching:   true,
			Batch:     true,
		},
		KnowledgeCutoff: time.Date(2025, 5, 1, 0, 0, 0, 0, time.UTC),
		ReleaseDate:     time.Date(2026, 2, 5, 0, 0, 0, 0, time.UTC),
	},
	{
		ID:            "claude-opus-4-5",
		Provider:      ProviderID,
		ContextWindow: 200_000,
		InputLimit:    200_000,
		OutputLimit:   64_000,
		Cost: kit.ModelCost{
			Input:      5.00,
			Output:     25.00,
			CacheRead:  0.50,
			CacheWrite: 6.25,
		},
		Capabilities: kit.ModelCapabilities{
			Text:      true,
			Image:     true,
			PDF:       true,
			Tools:     true,
			Streaming: true,
			Reasoning: true,
			Caching:   true,
			Batch:     true,
		},
		KnowledgeCutoff: time.Date(2025, 3, 31, 0, 0, 0, 0, time.UTC),
		ReleaseDate:     time.Date(2025, 11, 24, 0, 0, 0, 0, time.UTC),
	},
	{
		ID:            "claude-sonnet-4-6",
		Provider:      ProviderID,
		ContextWindow: 200_000,
		InputLimit:    200_000,
		OutputLimit:   64_000,
		Cost: kit.ModelCost{
			Input:      3.00,
			Output:     15.00,
			CacheRead:  0.30,
			CacheWrite: 3.75,
		},
		Capabilities: kit.ModelCapabilities{
			Text:      true,
			Image:     true,
			PDF:       true,
			Tools:     true,
			Streaming: true,
			Reasoning: true,
			Caching:   true,
			Batch:     true,
		},
		KnowledgeCutoff: time.Date(2025, 8, 1, 0, 0, 0, 0, time.UTC),
		ReleaseDate:     time.Date(2026, 2, 17, 0, 0, 0, 0, time.UTC),
	},
	{
		ID:            "claude-sonnet-4-5",
		Provider:      ProviderID,
		ContextWindow: 200_000,
		InputLimit:    200_000,
		OutputLimit:   64_000,
		Cost: kit.ModelCost{
			Input:      3.00,
			Output:     15.00,
			CacheRead:  0.30,
			CacheWrite: 3.75,
		},
		Capabilities: kit.ModelCapabilities{
			Text:      true,
			Image:     true,
			PDF:       true,
			Tools:     true,
			Streaming: true,
			Reasoning: true,
			Caching:   true,
			Batch:     true,
		},
		KnowledgeCutoff: time.Date(2025, 7, 31, 0, 0, 0, 0, time.UTC),
		ReleaseDate:     time.Date(2025, 9, 29, 0, 0, 0, 0, time.UTC),
	},
	{
		ID:            "claude-haiku-4-5",
		Provider:      ProviderID,
		ContextWindow: 200_000,
		InputLimit:    200_000,
		OutputLimit:   64_000,
		Cost: kit.ModelCost{
			Input:      1.00,
			Output:     5.00,
			CacheRead:  0.10,
			CacheWrite: 1.25,
		},
		Capabilities: kit.ModelCapabilities{
			Text:      true,
			Image:     true,
			PDF:       true,
			Tools:     true,
			Streaming: true,
			Reasoning: true,
			Caching:   true,
			Batch:     true,
		},
		KnowledgeCutoff: time.Date(2025, 2, 28, 0, 0, 0, 0, time.UTC),
		ReleaseDate:     time.Date(2025, 10, 15, 0, 0, 0, 0, time.UTC),
	},
}
