package openai

import (
	"time"

	"github.com/vitaliiPsl/crappy-adk/kit"
)

var knownModels = []kit.ModelConfig{
	{
		ID:            "gpt-5.4",
		Provider:      providerID,
		ContextWindow: 1_050_000,
		InputLimit:    922_000,
		OutputLimit:   128_000,
		Cost: kit.ModelCost{
			Input:     2.50,
			Output:    15.00,
			CacheRead: 0.25,
		},
		Capabilities: kit.ModelCapabilities{
			Text:      true,
			Image:     true,
			PDF:       true,
			Tools:     true,
			Streaming: true,
			Reasoning: true,
			Caching:   true,
			Batch:     true,
		},
		KnowledgeCutoff: time.Date(2025, 8, 31, 0, 0, 0, 0, time.UTC),
		ReleaseDate:     time.Date(2026, 3, 5, 0, 0, 0, 0, time.UTC),
	},
	{
		ID:            "gpt-5.4-pro",
		Provider:      providerID,
		ContextWindow: 1_050_000,
		InputLimit:    922_000,
		OutputLimit:   128_000,
		Cost: kit.ModelCost{
			Input:  30.00,
			Output: 180.00,
		},
		Capabilities: kit.ModelCapabilities{
			Text:      true,
			Image:     true,
			Tools:     true,
			Streaming: true,
			Reasoning: true,
			Batch:     true,
		},
		KnowledgeCutoff: time.Date(2025, 8, 31, 0, 0, 0, 0, time.UTC),
		ReleaseDate:     time.Date(2026, 3, 5, 0, 0, 0, 0, time.UTC),
	},
	{
		ID:            "gpt-5.4-mini",
		Provider:      providerID,
		ContextWindow: 400_000,
		InputLimit:    272_000,
		OutputLimit:   128_000,
		Cost: kit.ModelCost{
			Input:     0.75,
			Output:    4.50,
			CacheRead: 0.075,
		},
		Capabilities: kit.ModelCapabilities{
			Text:      true,
			Image:     true,
			Tools:     true,
			Streaming: true,
			Reasoning: true,
			Caching:   true,
			Batch:     true,
		},
		KnowledgeCutoff: time.Date(2025, 8, 31, 0, 0, 0, 0, time.UTC),
		ReleaseDate:     time.Date(2026, 3, 17, 0, 0, 0, 0, time.UTC),
	},
	{
		ID:            "gpt-5.4-nano",
		Provider:      providerID,
		ContextWindow: 400_000,
		InputLimit:    272_000,
		OutputLimit:   128_000,
		Cost: kit.ModelCost{
			Input:     0.20,
			Output:    1.25,
			CacheRead: 0.02,
		},
		Capabilities: kit.ModelCapabilities{
			Text:      true,
			Image:     true,
			Tools:     true,
			Streaming: true,
			Reasoning: true,
			Caching:   true,
			Batch:     true,
		},
		KnowledgeCutoff: time.Date(2025, 8, 31, 0, 0, 0, 0, time.UTC),
		ReleaseDate:     time.Date(2025, 3, 17, 0, 0, 0, 0, time.UTC),
	},
	{
		ID:            "gpt-5",
		Provider:      providerID,
		ContextWindow: 400_000,
		InputLimit:    272_000,
		OutputLimit:   128_000,
		Cost: kit.ModelCost{
			Input:     1.25,
			Output:    10.00,
			CacheRead: 0.125,
		},
		Capabilities: kit.ModelCapabilities{
			Text:      true,
			Image:     true,
			Tools:     true,
			Streaming: true,
			Reasoning: true,
			Caching:   true,
			Batch:     true,
		},
		KnowledgeCutoff: time.Date(2024, 9, 30, 0, 0, 0, 0, time.UTC),
		ReleaseDate:     time.Date(2025, 8, 7, 0, 0, 0, 0, time.UTC),
	},
	{
		ID:            "gpt-5-mini",
		Provider:      providerID,
		ContextWindow: 400_000,
		InputLimit:    272_000,
		OutputLimit:   128_000,
		Cost: kit.ModelCost{
			Input:     0.25,
			Output:    2.00,
			CacheRead: 0.025,
		},
		Capabilities: kit.ModelCapabilities{
			Text:      true,
			Image:     true,
			Tools:     true,
			Streaming: true,
			Reasoning: true,
			Caching:   true,
			Batch:     true,
		},
		KnowledgeCutoff: time.Date(2024, 5, 30, 0, 0, 0, 0, time.UTC),
		ReleaseDate:     time.Date(2025, 8, 7, 0, 0, 0, 0, time.UTC),
	},
	{
		ID:            "gpt-5-nano",
		Provider:      providerID,
		ContextWindow: 400_000,
		InputLimit:    272_000,
		OutputLimit:   128_000,
		Cost: kit.ModelCost{
			Input:     0.05,
			Output:    0.40,
			CacheRead: 0.005,
		},
		Capabilities: kit.ModelCapabilities{
			Text:      true,
			Image:     true,
			Tools:     true,
			Streaming: true,
			Reasoning: true,
			Caching:   true,
			Batch:     true,
		},
		KnowledgeCutoff: time.Date(2024, 5, 30, 0, 0, 0, 0, time.UTC),
		ReleaseDate:     time.Date(2025, 8, 7, 0, 0, 0, 0, time.UTC),
	},
	{
		ID:            "gpt-4.1",
		Provider:      providerID,
		ContextWindow: 1_047_576,
		InputLimit:    1_047_576,
		OutputLimit:   32_768,
		Cost: kit.ModelCost{
			Input:     2.00,
			Output:    8.00,
			CacheRead: 0.50,
		},
		Capabilities: kit.ModelCapabilities{
			Text:      true,
			Image:     true,
			Tools:     true,
			Streaming: true,
			Reasoning: false,
			Caching:   true,
			Batch:     true,
		},
		KnowledgeCutoff: time.Date(2024, 4, 1, 0, 0, 0, 0, time.UTC),
		ReleaseDate:     time.Date(2025, 4, 14, 0, 0, 0, 0, time.UTC),
	},
}
